version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
    - dependency-name: org.apache.maven:maven-compat
      versions:
      - 3.8.1
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
